#!/bin/bash
if [ -e $1 ]
then
  echo "Error: $1 already exists"
else
  mkdir "$1"
  cd "$1"
  a=`expr ${#1} - 2`
  echo "[Question: $1 \"$2\"](http://uva.onlinejudge.org/external/${1:0:$a}/$1.html)
===" > "README.md"
  touch "$1.java" "$1.in" "$1.out"
  echo "/* Alex Velazquez" >> "$1.java"
  echo " * Start: `date`" >> "$1.java"
  echo " * End  :" >> "$1.java"
  echo "*/" >> "$1.java"
  cat "../template.java" >> "$1.java"
fi
