#!/bin/bash
TEMPFILE="./temp.file"
if [ $# -ne 2 ]
then
   echo "Usage: $0 <dir> <commitMessage>" 
   exit 1
fi
rm -rf $1/a.out $1/$1 $1/$1.out2 
sed "s/ \* End  :/ \* End  : `date`/g" "$1/$1.cpp" > "$TEMPFILE" && mv $TEMPFILE "$1/$1.cpp"
rm -f $TEMPFILE
git add $1
git commit -m "SPOJ problem: $2"
git push origin master
